import { Service } from "../types/service";
import { Booking } from "@/types/booking";

export const services: Service[] = [
  {
    id: "1",
    name: "Haircut",
    price: 500,
    duration: 30,
    salonName: "Glow & Glam Studio",
    salonImage: "/assets/s1.jpg",
    salonLocation: "Maryland City, MD, USA",
    salonRating: 4.9,
    salonReviews: 255,
    category: "Hair Cut",
  },
  {
    id: "2",
    name: "Beard Trim",
    price: 300,
    duration: 20,
    salonName: "The Velvet Touch",
    salonImage: "/assets/s2.jpg",
    salonLocation: "New Jersey, USA",
    salonRating: 4.7,
    salonReviews: 180,
    category: "Hair Cut",
  },
  {
    id: "3",
    name: "Hair Spa",
    price: 1200,
    duration: 60,
    salonName: "Aura Luxe Salon",
    salonImage: "/assets/s3.jpg",
    salonLocation: "California, USA",
    salonRating: 4.5,
    salonReviews: 320,
    category: "Hair Spa",
  },
  {
    id: "4",
    name: "Facial",
    price: 900,
    duration: 45,
    salonName: "Opal Beauty Lounge",
    salonImage: "/assets/s4.jpg",
    salonLocation: "Maryland, USA",
    salonRating: 4.8,
    salonReviews: 210,
    category: "Facial",
  },
  {
    id: "5",
    name: "Hair Color",
    price: 1500,
    duration: 90,
    salonName: "The Glam Society",
    salonImage: "/assets/s1.jpg",
    salonLocation: "Texas, USA",
    salonRating: 4.2,
    salonReviews: 150,
    category: "Hair Color",
  },
  {
    id: "6",
    name: "Head Massage",
    price: 400,
    duration: 20,
    salonName: "Crown & Curl",
    salonImage: "/assets/s2.jpg",
    salonLocation: "Texas, USA",
    salonRating: 4.9,
    salonReviews: 280,
    category: "Massage",
  },
  {
    id: "7",
    name: "Keratin Treatment",
    price: 2500,
    duration: 120,
    salonName: "Glow & Glam Studio",
    salonImage: "/assets/s3.jpg",
    salonLocation: "Maryland City, MD, USA",
    salonRating: 4.9,
    salonReviews: 190,
    category: "Hair Treatment",
  },
  {
    id: "8",
    name: "Manicure & Pedicure",
    price: 700,
    duration: 50,
    salonName: "The Velvet Touch",
    salonImage: "/assets/s4.jpg",
    salonLocation: "New Jersey, USA",
    salonRating: 4.6,
    salonReviews: 240,
    category: "Nails",
  },
];

export let bookings: Booking[] = [
  {
    id: "b1",
    userId: "123",
    serviceId: "1",
    serviceName: "Haircut",
    salonName: "Glow & Glam Studio",
    salonImage: "/assets/s1.jpg",
    salonLocation: "Maryland City, MD, USA",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "+1234567890",
    date: "2026-02-10",
    time: "11:00",
    status: "CONFIRMED",
    price: 500,
    originalPrice: 700,
    discount: 200,
    createdAt: "2026-02-01",
  },
  {
    id: "b2",
    userId: "123",
    serviceId: "3",
    serviceName: "Hair Spa",
    salonName: "Aura Luxe Salon",
    salonImage: "/assets/s3.jpg",
    salonLocation: "California, USA",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "+1234567890",
    date: "2026-02-15",
    time: "14:00",
    status: "PENDING",
    price: 1200,
    originalPrice: 1500,
    discount: 300,
    createdAt: "2026-02-05",
  },
  {
    id: "b3",
    userId: "123",
    serviceId: "2",
    serviceName: "Beard Trim",
    salonName: "The Velvet Touch",
    salonImage: "/assets/s2.jpg",
    salonLocation: "New Jersey, USA",
    firstName: "John",
    lastName: "Doe",
    email: "john@example.com",
    phone: "+1234567890",
    date: "2026-02-05",
    time: "10:00",
    status: "CANCELLED",
    price: 300,
    originalPrice: 400,
    discount: 100,
    createdAt: "2026-02-01",
  },
];